services:
    init-app:
        build: .
        restart: on-failure
        ports:
            - 4000:4000
        depends_on:
            mongo_self:
                condition: service_healthy
        networks:
            - backend
        environment:
            DB_TYPE: 'mongodb'
            DB_HOST: 'mongo_self'
            DB_PORT: 27017
            DB_USERNAME: 'mcdonalds'
            DB_PASSWORD: 'MfDZk"rTtn[f>j%'
            DB_DATABASE: 'self-service-payment'
            PORT: 4000
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1GB
    app:
        build: .
        restart: on-failure
        ports:
            - 4000:4000
        depends_on:
            mongo_self:
                condition: service_healthy
        networks:
            - backend
        environment:
            DB_TYPE: 'mongodb'
            DB_HOST: 'mongo_self'
            DB_PORT: 27017
            DB_USERNAME: 'mcdonalds'
            DB_PASSWORD: 'MfDZk"rTtn[f>j%'
            DB_DATABASE: 'self-service-payment'
            PORT: 4000
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1GB
    mongo_self:
      image: mongo:6.0
      restart: on-failure
      ports:
          - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: 'mcdonalds'
        MONGO_INITDB_ROOT_PASSWORD: 'MfDZk"rTtn[f>j%'
        MONGO_INITDB_DATABASE: self-service-payment
      networks:
          - backend
      volumes:
          - /var/lib/mongo-self
      healthcheck:
          test: echo 'db.runCommand("ping").ok' | mongo --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin localhost/self-service-payment
          interval: 10s
          timeout: 5s
          retries: 5

networks:
    backend:
        driver: bridge